/**
 * @file models/index.ts
 * @description Model re-exports for auth service.
 *
 * The auth service uses Prisma instead of Mongoose.
 * Models are auto-generated by Prisma Client from prisma/schema.prisma.
 *
 * Import models directly from '@prisma/client':
 *   import { PrismaClient, User, UserRole, AuthProvider } from '@prisma/client';
 */

// Re-export Prisma types for convenience
export { User, UserRole, AuthProvider } from '@prisma/client';
